import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
+
+// styles del design/home-02.html
+
+import "/public/fonts/fonts.css"
+import "/public/fonts/font-icons.css"
+import "/public/css/bootstrap.min.css"
+import "/public/css/swiper-bundle.min.css"
+import "/public/css/animate.css"
+import "/public/css/styles.css"
+
+// styles del design/home-02.html
+
+

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
