import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "/public/css/animate.css";
import "/public/css/bootstrap.min.css";
import "/public/css/styles.css";
import "/public/css/swiper-bundle.min.css";
import "/public/fonts/font-icons.css";
import "/public/fonts/fonts.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// styles del design/home-02.html

// styles del design/home-02.html

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}

        {/* scripts del design/home-02.html */}
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/swiper-bundle.min.js"></script>
        <script type="text/javascript" src="/js/carousel.js"></script>
        <script
          type="text/javascript"
          src="/js/bootstrap-select.min.js"
        ></script>
        <script type="text/javascript" src="/js/lazysize.min.js"></script>
        <script type="text/javascript" src="/js/count-down.js"></script>
        <script type="text/javascript" src="/js/wow.min.js"></script>
        <script type="text/javascript" src="/js/multiple-modal.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>

        {/* scripts del design/home-02.html */}
      </body>
    </html>
  );
}
